#!/bin/bash

# NOTE: since jq modules path are relative, filter should be run in this directory
cd $(dirname $0)

# run jq filter
# NOTE: assign command argument to variable $key
cat - | jq --arg key $1 -r -f main.jq
